const left1 = [
    //upper
    {
        id: 'R1:FLU:CBN1',
        on: false,
        text: 'cabinet 1',
        arrName: 'R1:FLU:CBN1',
        gridArea: '1 / 1 / span 2 / span 1',
    },
    {
        id: 'R1:FLU:CBN2',
        on: false,
        text: 'cabinet 2',
        arrName: 'R1:FLU:CBN2',
        gridArea: '1 / 2 / span 2 / span 1',
    },
    {
        id: 'R1:FLU:CBN3',
        on: false,
        text: 'cabinet 3',
        arrName: 'R1:FLU:CBN3',
        gridArea: '1 / 3 / span 2 / span 1',
    },
    {
        id: 'R1:FLU:CBN4',
        on: false,
        text: 'cabinet 4',
        arrName: 'R1:FLU:CBN4',
        gridArea: '1 / 4 / span 2 / span 1',
    },
    {
        id: 'R1:FLU:CBN5',
        on: false,
        text: 'cabinet 5',
        arrName: 'R1:FLU:CBN5',
        gridArea: '1 / 5 / span 2 / span 1',
    },
    {
        id: 'R1:FLU:CBN6',
        on: false,
        text: 'cabinet 6',
        arrName: 'R1:FLU:CBN6',
        gridArea: '1 / 6 / span 2 / span 1',
    },
    {
        id: 'R1:BLU:CBN7',
        on: false,
        text: 'cabinet 7',
        arrName: 'R1:BLU:CBN7',
        gridArea: '1 / 9 / span 2 / span 1',
    },
    {
        id: 'R1:BLU:CBN8',
        on: false,
        text: 'cabinet 8',
        arrName: 'R1:BLU:CBN8',
        gridArea: '1 / 10 / span 2 / span 1',
    },
    {
        id: 'R1:BLU:CBN9',
        on: false,
        text: 'cabinet 9',
        arrName: 'R1:BLU:CBN9',
        gridArea: '1 / 11 / span 2 / span 1',
    },
    {
        id: 'R1:BLU:CBN0',
        on: false,
        text: 'cabinet 0',
        arrName: 'R1:BLU:CBN0',
        gridArea: '1 / 12 / span 2 / span 1',
    },
    //middle---------------------------------------------
    {
        id: 'R1:MLM:CRT1',
        on: false,
        text: 'cart',
        arrName: 'R1:MLM:CRT1',
        gridArea: '4 / 7 / span 1 / span 2',
    },
    {
        id: 'R1:FLM:DRW1',
        on: false,
        text: 'drawer 1',
        arrName: 'R1:FLM:DRW1',
        gridArea: '4 / 1 / span 1 / span 2',
    },
    {
        id: 'R1:FLM:DRW2',
        on: false,
        text: 'drawer 2',
        arrName: 'R1:FLM:DRW2',
        gridArea: '4 / 3 / span 1 / span 2',
    },
    //lower-----------------------------------------------
    {
        id: 'R1:FLL:CBN1',
        on: false,
        text: 'cabinet 1',
        arrName: 'R1:FLL:CBN1',
        gridArea: '5 / 1 / span 2 / span 1',
    },
    {
        id: 'R1:FLL:CBN2',
        on: false,
        text: 'cabinet 2',
        arrName: 'R1:FLL:CBN2',
        gridArea: '5 / 2 / span 2 / span 1',
    },
    {
        id: 'R1:FLL:CBN3',
        on: false,
        text: 'cabinet 3',
        arrName: 'R1:FLL:CBN3',
        gridArea: '5 / 5 / span 2 / span 1',
    },
    {
        id: 'R1:FLL:CBN4',
        on: false,
        text: 'cabinet 4',
        arrName: 'R1:FLL:CBN4',
        gridArea: '5 / 6 / span 2 / span 1',
    },
    {
        id: 'R1:MLL:DRW3',
        on: false,
        text: 'drawer 3',
        arrName: 'R1:MLL:DRW3',
        gridArea: '5 / 9 / span 1 / span 1',
    },
    {
        id: 'R1:MLL:CRT1',
        on: false,
        text: 'cart',
        arrName: 'R1:MLL:CRT1',
        gridArea: '6 / 7 / span 1 / span 2',
    },
    {
        id: 'R1:MLL:DRW4',
        on: false,
        text: 'drawer 4',
        arrName: 'R1:MLL:DRW4',
        gridArea: '6 / 9 / span 1 / span 1',
    },
    {
        id: 'R1:BLL:CBN5',
        on: false,
        text: 'cabinet 5',
        arrName: 'R1:BLL:CBN5',
        gridArea: '5 / 10 / span 2 / span 1',
    },
    {
        id: 'R1:BLL:CBN6',
        on: false,
        text: 'cabinet 6',
        arrName: 'R1:BLL:CBN6',
        gridArea: '5 / 11 / span 2 / span 1',
    },
    {
        id: 'R1:BLL:CHM1',
        on: false,
        text: 'chemical \n storage',
        arrName: 'R1:BLL:CHM1',
        gridArea: '5 / 12 / span 2 / span 1',
    },
    {
        id: 'R1:BLL:CBN7',
        on: false,
        text: 'cabinet 7',
        arrName: 'R1:BLL:CBN7',
        gridArea: '5 / 13 / span 2 / span 1',
    },
    {
        id: 'R1:BLL:FLR1',
        on: false,
        text: 'floor',
        arrName: 'R1:BLL:FLR1',
        gridArea: '6 / 14 / span 1 / span 2',
    },
]
export default left1