const right1 = [
    //upper
    {
        id: 'R1:BRU:SHL1',
        on: false,
        text: 'shelf 1',
        arrName: 'R1:BRU:SHL1',
        gridArea: '1 / 1 / span 2 / span 2',//row / col / span
    },
    {
        id: 'R1:BRU:CBN1',
        on: false,
        text: 'cabinet 1',
        arrName: 'R1:BRU:CBN1',
        gridArea: '1 / 3 / span 2 / span 1',
    },
    {
        id: 'R1:BRU:CBN2',
        on: false,
        text: 'cabinet 2',
        arrName: 'R1:BRU:CBN2',
        gridArea: '1 / 4 / span 2 / span 1',
    },
    {
        id: 'R1:BRU:CBN3',
        on: false,
        text: 'cabinet 3',
        arrName: 'R1:BRU:CBN3',
        gridArea: '1 / 5 / span 2 / span 1',
    },
    {
        id: 'R1:BRU:CBN4',
        on: false,
        text: 'cabinet 4',
        arrName: 'R1:BRU:CBN4',
        gridArea: '1 / 6 / span 2 / span 1',
    },
    {
        id: 'R1:MRU:CBN5',
        on: false,
        text: 'cabinet 5',
        arrName: 'R1:MRU:CBN5',
        gridArea: '1 / 7 / span 2 / span 1',
    },
    {
        id: 'R1:MRU:CBN6',
        on: false,
        text: 'cabinet 6',
        arrName: 'R1:MRU:CBN6',
        gridArea: '1 / 8 / span 2 / span 1',
    },
    {
        id: 'R1:MRU:SHL2',
        on: false,
        text: 'shelf 2',
        arrName: 'R1:MRU:SHL2',
        gridArea: '1 / 9 / span 2 / span 2',
    },
    {
        id: 'R1:FRU:CBN7',
        on: false,
        text: 'cabinet 7',
        arrName: 'R1:FRU:CBN7',
        gridArea: '1 / 11 / span 2 / span 1',
    },
    {
        id: 'R1:FRU:CBN8',
        on: false,
        text: 'cabinet 8',
        arrName: 'R1:FRU:CBN8',
        gridArea: '1 / 12 / span 2 / span 1',
    },
    {
        id: 'R1:FRU:CBN9',
        on: false,
        text: 'cabinet 9',
        arrName: 'R1:FRU:CBN9',
        gridArea: '1 / 13 / span 2 / span 1',
    },
    {
        id: 'R1:FRU:CBN0',
        on: false,
        text: 'cabinet 0',
        arrName: 'R1:FRU:CBN0',
        gridArea: '1 / 14 / span 2 / span 1',
    },
    {
        id: 'R1:FRU:CBN1',
        on: false,
        text: 'cabinet 1',
        arrName: 'R1:FRU:CBN1',
        gridArea: '1 / 15 / span 2 / span 1',
    },
    {
        id: 'R1:FRU:CBN2',
        on: false,
        text: 'cabinet 2',
        arrName: 'R1:FRU:CBN2',
        gridArea: '1 / 16 / span 2 / span 1',
    },
    
    //middle---------------------------------------------
    {
        id: 'R1:FRM:DRW6',
        on: false,
        text: 'drawer 6',
        arrName: 'R1:FRM:DRW6',
        gridArea: '4 / 13 / span 1 / span 2',
    },
    {
        id: 'R1:FRM:DRW7',
        on: false,
        text: 'drawer 7',
        arrName: 'R1:FRM:DRW7',
        gridArea: '4 / 15 / span 1 / span 2',
    },
    //lower----------------------------------------------
    {
        id: 'R1:BRL:DRW1',
        on: false,
        text: 'drawer 1',
        arrName: 'R1:BRL:DRW1',
        gridArea: '5 / 1 / span 1 / span 1',
    },
    {
        id: 'R1:BRL:DRW2',
        on: false,
        text: 'drawer 2',
        arrName: 'R1:BRL:DRW2',
        gridArea: '6 / 1 / span 1 / span 1',
    },
    {
        id: 'R1:BRL:DRW3',
        on: false,
        text: 'drawer 3',
        arrName: 'R1:BRL:DRW3',
        gridArea: '7 / 1 / span 1 / span 1',
    },
    {
        id: 'R1:BRL:DRW4',
        on: false,
        text: 'drawer 4',
        arrName: 'R1:BRL:DRW4',
        gridArea: '5 / 2 / span 1 / span 1',
    },
    {
        id: 'R1:BRL:DRW5',
        on: false,
        text: 'drawer 5',
        arrName: 'R1:BRL:DRW5',
        gridArea: '5 / 3 / span 1 / span 1',
    },
    {
        id: 'R1:BRL:DRW6',
        on: false,
        text: 'drawer 6',
        arrName: 'R1:BRL:DRW6',
        gridArea: '6 / 3 / span 1 / span 1',
    },
    {
        id: 'R1:BRL:DRW7',
        on: false,
        text: 'drawer 7',
        arrName: 'R1:BRL:DRW7',
        gridArea: '5 / 4 / span 1 / span 1',
    },
    {
        id: 'R1:BRL:DRW8',
        on: false,
        text: 'drawer 8',
        arrName: 'R1:BRL:DRW8',
        gridArea: '6 / 4 / span 1 / span 1',
    },
    {
        id: 'R1:BRL:DRW9',
        on: false,
        text: 'drawer 9',
        arrName: 'R1:BRL:DRW9',
        gridArea: '7 / 4 / span 1 / span 1',
    },
    {
        id: 'R1:BRL:DRW0',
        on: false,
        text: 'drawer 0',
        arrName: 'R1:BRL:DRW0',
        gridArea: '5 / 5 / span 1 / span 2',
    },
    {
        id: 'R1:MRL:DRW1',
        on: false,
        text: 'drawer 1',
        arrName: 'R1:MRL:DRW1',
        gridArea: '5 / 7 / span 1 / span 1',
    },
    {
        id: 'R1:MRL:DRW2',
        on: false,
        text: 'drawer 2',
        arrName: 'R1:MRL:DRW2',
        gridArea: '6 / 7 / span 1 / span 1',
    },
    {
        id: 'R1:MRL:DRW3',
        on: false,
        text: 'drawer 3',
        arrName: 'R1:MRL:DRW3',
        gridArea: '5 / 8 / span 1 / span 1',
    },
    {
        id: 'R1:MRL:DRW4',
        on: false,
        text: 'drawer 4',
        arrName: 'R1:MRL:DRW4',
        gridArea: '6 / 8 / span 1 / span 1',
    },
    {
        id: 'R1:MRL:DRW5',
        on: false,
        text: 'drawer 5',
        arrName: 'R1:MRL:DRW5',
        gridArea: '7 / 8 / span 1 / span 1',
    },
    {
        id: 'R1:MRL:DRW6',
        on: false,
        text: 'drawer 6',
        arrName: 'R1:MRL:DRW6',
        gridArea: '5 / 9 / span 1 / span 1',
    },
    {
        id: 'R1:MRL:DRW7',
        on: false,
        text: 'drawer 7',
        arrName: 'R1:MRL:DRW7',
        gridArea: '5 / 10 / span 1 / span 1',
    },
    {
        id: 'R1:MRL:DRW8',
        on: false,
        text: 'drawer 8',
        arrName: 'R1:MRL:DRW8',
        gridArea: '6 / 10 / span 1 / span 1',
    },
    {
        id: 'R1:FRL:CBN1',
        on: false,
        text: 'cabinet 1',
        arrName: 'R1:FRL:CBN1',
        gridArea: '5 / 11 / span 2 / span 1',
    },
    {
        id: 'R1:FRL:CBN2',
        on: false,
        text: 'cabinet 2',
        arrName: 'R1:FRL:CBN2',
        gridArea: '5 / 12 / span 2 / span 1',
    },
    {
        id: 'R1:FRL:CBN3',
        on: false,
        text: 'cabinet 3',
        arrName: 'R1:FRL:CBN3',
        gridArea: '5 / 15 / span 2 / span 1',
    },
    {
        id: 'R1:FRL:CBN4',
        on: false,
        text: 'cabinet 4',
        arrName: 'R1:FRL:CBN4',
        gridArea: '5 / 16 / span 2 / span 1',
    },

    //

]
export default right1